[package]
name = "onomancy_core"
version = "0.2.0"
description = "Core logic for Onomancer"
readme = "./README.md"

repository.workspace = true
license.workspace = true
authors.workspace = true

categories = ["data-structures"]
keywords = ["onomancy", "names"]

edition.workspace = true
rust-version.workspace = true

[dependencies]
arbitrary = { workspace = true, optional = true, features = ["derive"] }
base64 = { workspace = true }
bijoux = { workspace = true }
blake3 = { workspace = true }
bs58 = { workspace = true }
ed25519-dalek = { workspace = true }

serde = { workspace = true, optional = true, features = ["alloc", "derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bolero = { workspace = true, features = ["arbitrary"] }
ed25519-dalek = { workspace = true }
onomancy_core = { path = ".", features = ["arbitrary"] }
testresult = { workspace = true }

[features]
default = []
arbitrary = ["dep:arbitrary", "std"] # derive needs std's thread_local

serde = ["dep:serde"]
std = ["ed25519-dalek/std", "thiserror/std"]

[lints]
workspace = true
