[package]
name = "onomancer_core"
version = "0.1.0"
description = "Core logic for Onomancer"

authors.workspace = true
categories = ["data-structures"]
edition.workspace = true
keywords = ["onomancer", "names"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
arbitrary = { workspace = true, optional = true, features = ["derive"] }
serde = { workspace = true, optional = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bolero = { workspace = true, features = ["arbitrary"] }
onomancer_core = { path = ".", features = ["arbitrary"] }
testresult = { workspace = true }

[features]
default = []
arbitrary = ["dep:arbitrary", "std"] # derive needs std's thread_local
serde = ["dep:serde"]
std = ["thiserror/std"]

[lints]
workspace = true
