[package]
name = "onomancy_wasm"
version = "0.1.0"
description = "Wasm/JavaScript bindings for Onomancer (browser and Node.js)"
categories = ["web-programming"]
keywords = ["onomancy", "wasm"]
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
js-sys = { workspace = true }
onomancy_core = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = []
std = [
  "js-sys/std",
  "onomancy_core/std",
  "thiserror/std",
  "wasm-bindgen/std",
  "wasm-bindgen-futures/std",
]

[lints]
workspace = true
